import type { NextPage } from "next";
import Head from "next/head";
import HomeModule from "../modules/HomeModule/HomeModule";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gameree | Home-Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeModule />
    </div>
  );
};

export default Home;
